package com.sb.lms.security;

import org.springframework.security.crypto.bcrypt.*;

/**
 * Contains methods of BCrypt PasswordHasher and verification
 * @author Saarah Bedekar
 */
public class BCryptPasswordHasher {
    private static final BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder();

    /**
     * Handles the hashing of a provided password
     * @param password the password for which the hash encoding has to be done for
     * @return a String of the hashedPassword
     */
    public static String hashPassword(String password) {
        return passwordEncoder.encode(password);
    }

    /**
     * Handles the match verification of a raw password with its hashed password
     * @param rawPassword the raw password provided by the user
     * @param hashedPassword the hashed password generated by the BCryptPasswordHasher
     * @return a boolean indicator to indicate the result of the match verification
     */
    public static boolean verifyPassword(String rawPassword, String hashedPassword) {
        return passwordEncoder.matches(rawPassword, hashedPassword);
    }
}
