spring.application.name=lms

spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://localhost:3306/lms
spring.datasource.username=root
spring.datasource.password=Root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
#spring.jpa.hibernate.ddl-auto= update
#hibernate.transaction.jta.platform=org.hibernate.service.jta.platform.internal.SunOneJtaPlatform
//spring.jpa.properties.hibernate.hbm2ddl.auto: update

#hibernate.transaction.jta.platform=org.hibernate.service.jta.platform.internal.JBossStandAloneJtaPlatform

#https://medium.com/@AlexanderObregon/enhancing-logging-with-log-and-slf4j-in-spring-boot-applications-f7e70c6e4cc7
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.file.level.com.sb.lms=INFO
logging.file.name=logs/lms.log
logging.file.max-size=10MB
logging.file.max-history=10
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n

#server.servlet.context-path=/lms

#logging.level.org.hibernate.type.descriptor.sql=TRACE

#H2 Database Configuration for testing
spring.datasource.test.url=jdbc:h2:mem/unit_test_db
spring.datasource.test.diver-class-name=org.h2.Driver
spring.datasource.test.username=sa
spring.datasource.test.password=password
spring.jpa.test.hibernate.ddl-auto = create-drop

#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.enabled=true
#spring.thymeleaf.cache=false

#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework=DEBUG

#spring.web.resources.static-locations=file:C:/Saarah/report_files

server.error.whitelabel.enabled=false
spring.mvc.throw-exception-if-no-handler-found=true
#spring.web.resources.add-mappings=false
server.error.include-static=true

server.error.include-exception=true
server.error.path=/error